#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PYTHON_BIN="${CSI_PAIRS_PYTHON:-python3}"
CONFIG="${CSI_PAIRS_FORMAL_CONFIG:-${PROJECT_ROOT}/formal_v2/configs/formal_v2.json}"
OUTPUT="${CSI_PAIRS_FORMAL_OUTPUT:?set CSI_PAIRS_FORMAL_OUTPUT to an unused output directory}"
VERIFIER_MANIFEST="${CSI_PAIRS_VERIFIER_MANIFEST:?set CSI_PAIRS_VERIFIER_MANIFEST to an independent RT verifier manifest}"
ADAPTER_MANIFEST="${CSI_PAIRS_EXTERNAL_ADAPTER_MANIFEST:?set CSI_PAIRS_EXTERNAL_ADAPTER_MANIFEST}"
CONTROL_MANIFEST="${CSI_PAIRS_RESOURCE_CONTROL_MANIFEST:?set CSI_PAIRS_RESOURCE_CONTROL_MANIFEST}"
SCENE_ID_MANIFEST="${CSI_PAIRS_SCENE_ID_MANIFEST:?set CSI_PAIRS_SCENE_ID_MANIFEST}"
EXTERNAL_VALIDITY_MANIFEST="${CSI_PAIRS_EXTERNAL_VALIDITY_MANIFEST:?set CSI_PAIRS_EXTERNAL_VALIDITY_MANIFEST}"
LITERATURE_MANIFEST="${CSI_PAIRS_LITERATURE_RESOURCE_MANIFEST:?set CSI_PAIRS_LITERATURE_RESOURCE_MANIFEST}"
RT_CALIBRATION_MANIFEST="${CSI_PAIRS_RT_CALIBRATION_MANIFEST:?set CSI_PAIRS_RT_CALIBRATION_MANIFEST}"
SHUFFLED_PAIR_MANIFEST="${CSI_PAIRS_SHUFFLED_PAIR_MANIFEST:?set CSI_PAIRS_SHUFFLED_PAIR_MANIFEST}"
RETENTION_MANIFEST="${CSI_PAIRS_RETENTION_MANIFEST:?set CSI_PAIRS_RETENTION_MANIFEST}"
DATASET_ARGS=()
if [[ -n "${CSI_PAIRS_FORMAL_DATASET:-}" ]]; then
  DATASET_ARGS=(--dataset "${CSI_PAIRS_FORMAL_DATASET}")
fi

cd "${PROJECT_ROOT}"
"${PYTHON_BIN}" -m formal_v2.formal_cli all \
  --config "${CONFIG}" \
  --output "${OUTPUT}" \
  --verifier-manifest "${VERIFIER_MANIFEST}" \
  --adapter-manifest "${ADAPTER_MANIFEST}" \
  --control-manifest "${CONTROL_MANIFEST}" \
  --scene-id-manifest "${SCENE_ID_MANIFEST}" \
  --external-validity-manifest "${EXTERNAL_VALIDITY_MANIFEST}" \
  --literature-resource-manifest "${LITERATURE_MANIFEST}" \
  --rt-calibration-manifest "${RT_CALIBRATION_MANIFEST}" \
  --shuffled-pair-manifest "${SHUFFLED_PAIR_MANIFEST}" \
  --retention-manifest "${RETENTION_MANIFEST}" \
  "${DATASET_ARGS[@]}"
